<<<<<<< HEAD
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Luis Raygada
email: lraygada@tepper.cmu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  luis-raygada

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
=======
# Site Settings
baseurl: ""
url : "https://luis-raygada.github.io"

# Blog Settings
theme_settings :
  title : Luis Raygada
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/luis-raygada.jpg
    username : Luis Raygada
    description : Hi, I’m Luis, I am an MBA graduate, systems engineer, and entrepreneur. I thrive in fast-paced, innovative organizations where I can use my leadership and problem-solving skills to solve complex challenges.
    experience :
      - start : 2020-01-20
        end : 2020-04-30
        experience : Micron, Edge Computing Consultant (MBA Capstone Project)
      - start : 2019-05-20
        end : 2020-08-09
        experience : Amazon Web Services, Senior Product Manager Technical - Intern
      - start : 2017-04-01
        end : 2018-07-30
        experience : IBM, Innovation Team Leader
      - start : 2015-04-01
        end : 2017-03-30
        experience : IBM, Innovation Leader
      - start : 2012-04-01
        end : 2015-03-30
        experience : IBM, Innovation Specialist
      - start : 2011-01-01
        end : 2012-03-30
        experience : IBM, IT Developer / IT Specialist
    skills : 
      - skill : Cloud Computing
        value : 85  # Percent value
      - skill : Program Management
        value : 80  # Percent value
      - skill : Product Management
        value : 75  # Percent value
        
  # Icons
  icons :
    email: lraygada@tepper.cmu.edu # Full email address, e.g. "sample@google.com"
    linkedin: https://www.linkedin.com/in/luis-raygada/ # Full URL 
    github: luis-raygada
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
>>>>>>> 9bfb7cd... initial commit
